// <auto-generated />
using System;
using LibrasInterview.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibrasInterview.Infrastructure.Migrations
{
    [DbContext(typeof(LibrasInterviewDbContext))]
    [Migration("20260623184427_AdicionaFonteTranscricao")]
    partial class AdicionaFonteTranscricao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Entrevista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntrevistadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EntrevistadorId");

                    b.ToTable("Entrevistas", (string)null);
                });

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Transcricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confianca")
                        .HasColumnType("numeric");

                    b.Property<int>("EntrevistaId")
                        .HasColumnType("integer");

                    b.Property<int>("Fonte")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrevistaId");

                    b.ToTable("Transcricoes", (string)null);
                });

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Entrevista", b =>
                {
                    b.HasOne("LibrasInterview.Domain.Entities.Usuario", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibrasInterview.Domain.Entities.Usuario", "Entrevistador")
                        .WithMany()
                        .HasForeignKey("EntrevistadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Entrevistador");
                });

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Transcricao", b =>
                {
                    b.HasOne("LibrasInterview.Domain.Entities.Entrevista", "Entrevista")
                        .WithMany("Transcricoes")
                        .HasForeignKey("EntrevistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrevista");
                });

            modelBuilder.Entity("LibrasInterview.Domain.Entities.Entrevista", b =>
                {
                    b.Navigation("Transcricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
